name: 'databricks_workshop'
version: '1.6.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets: 
  - "target"
  - "dbt_modules"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  databricks_workshop:
    example:
      materialized: view
    staging:
      materialized: view
    marts:
      materialized: table
